/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)osapi_utility_impl.h    generated by: makeheader    Fri Feb 16 13:51:08 2018
 *
 *		built from:	utility_impl.ifc
 */

#ifndef osapi_utility_impl_h
#define osapi_utility_impl_h





#ifdef __cplusplus
    extern "C" {
#endif


#define RTIOsapiUtility_max(l, r) (((l) > (r)) ? (l) : (r))
#define RTIOsapiUtility_min(l, r) (((l) < (r)) ? (l) : (r))
#define RTIOsapiUtility_isWithinBound(n, lower, upper) (((n) >= (lower)) \
                                                        && ((n) <= (upper)))

#define RTIOsapiUtility_getSpaceLeft(length, max) \
    (((max) > (length)) \
            ? ((max) - (length)) \
            : 0)

#define RTIOsapiUtility_assertSpaceLeft(length, max, bytesToAssert) \
        (RTIOsapiUtility_getSpaceLeft(length, max) >= (bytesToAssert))

#define RTIOsapiUtility_unusedParameter(parameter) (void) parameter

/*
 * Use this macro to remove warnings in situations where 
 * a function is assigning its return value to a variable but 
 * the variable is not being used anywhere. This will produce a
 * "set-but-unused variable warning".
 * 
 * @param function The function returning a value which is not being used
 * @param type     The type of the expected return value of function
 *
 */
#define RTIOsapiUtility_unusedReturnValue(function, type) \
{                                                         \
    type unusedReturnValue;                               \
    unusedReturnValue = function;                         \
    (void)unusedReturnValue;                              \
} (void)0



#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* osapi_utility_impl_h */
