/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)reda_inlineMemoryBlock.h    generated by: makeheader    Fri Feb 16 13:51:18 2018
 *
 *		built from:	inlineMemoryBlock.ifc
 */

#ifndef reda_inlineMemoryBlock_h
#define reda_inlineMemoryBlock_h


  #ifndef reda_dll_h
    #include "reda/reda_dll.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* reda_inlineMemoryBlock_h */
