/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_buildid.h    generated by: makeheader    Fri Feb 16 13:52:08 2018
 *
 *		built from:	buildid.ifcxx
 */

#ifndef dds_cpp_buildid_h
#define dds_cpp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSCPP_BUILD_5.3.1.0_20180216T211030Z_RTI_REL"
#endif

#endif /* dds_cpp_buildid_h */
