/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)clock_system.h    generated by: makeheader    Fri Feb 16 13:51:13 2018
 *
 *		built from:	system.ifc
 */

#ifndef clock_system_h
#define clock_system_h


  #ifndef clock_interface_h
    #include "clock/clock_interface.h"
  #endif
  #ifndef clock_dll_h
    #include "clock/clock_dll.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif

struct RTISystemClock; /* forward declare to appease compiler */

extern RTIClockDllExport void RTISystemClock_delete(struct RTIClock *me);

extern RTIClockDllExport struct RTIClock *RTISystemClock_new();


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* clock_system_h */
