/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)rtitls_dll.h    generated by: makeheader    Fri Feb 16 13:53:06 2018
 *
 *		built from:	dll.ifc
 */

#ifndef rtitls_dll_h
#define rtitls_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE)
  #if defined(RTI_rtitls_DLL_EXPORT)
    #define RTITLSDllExport __declspec( dllexport )
  #else
    #define RTITLSDllExport
  #endif /* RTI_rtitls_DLL_EXPORT */

  #if defined(RTI_rtitls_DLL_VARIABLE) 
    #if defined(RTI_rtitls_DLL_EXPORT)
      #define RTITLSDllVariable __declspec( dllexport )
    #else
      #define RTITLSDllVariable __declspec( dllimport )
    #endif /* RTI_rtitls_DLL_EXPORT */
  #else 
    #define RTITLSDllVariable
    #endif /* RTI_rtitls_DLL_EXPORT */
#else
  #define RTITLSDllExport
  #define RTITLSDllVariable
#endif /* RTI_WIN32 || RTI_WINCE */

#endif /* rtitls_dll_h */
