/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)core_version_version_impl.h    generated by: makeheader    Fri Feb 16 13:51:48 2018
 *
 *		built from:	version_impl.ifc
 */

#ifndef core_version_version_impl_h
#define core_version_version_impl_h


#ifdef __cplusplus
    extern "C" {
#endif


#define VERSLibraryVersion_quote(token)     VERSLibraryVersion_xquote(token)


#define VERSLibraryVersion_xquote(token)    #token


#define VERSLibraryVersion_VERSION_LETTER \
        VERSLibraryVersion_quote(RTI_MODULE_LETTER_RELEASE)[0]


#define VERSLibraryVersion_FORMATTED_VERSION(libName) \
        VERSLibraryVersion_quote(                     \
            VERSLibraryVersion_UNQUOTED_FORMATTED_VERSION(libName))


#define VERSLibraryVersion_UNQUOTED_FORMATTED_VERSION(libName) \
        VERSLibraryVersion_format(libName,                     \
                                  RTI_MODULE_VERSION_MAJOR,    \
                                  RTI_MODULE_VERSION_MINOR,    \
                                  RTI_MODULE_LETTER_RELEASE,   \
                                  RTI_MODULE_VERSION_BUILD)


#define VERSLibraryVersion_format(libName, a,b,c,d) \
        VERSLibraryVersion_xformat(libName, a, b, c, d)


#define VERSLibraryVersion_xformat(libName, major, minor, release, build) \
        libName ## major.minor ## release.rev ## build


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* core_version_version_impl_h */
