/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_buildid.h    generated by: makeheader    Fri Feb 16 13:51:59 2018
 *
 *		built from:	buildid.ifc
 */

#ifndef dds_c_buildid_h
#define dds_c_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSC_BUILD_5.3.1.0_20180216T211030Z_RTI_REL"
#endif

#endif /* dds_c_buildid_h */
