/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)ndds_cpp.h    generated by: makeheader    Fri Feb 16 13:54:22 2018
 *
 *		built from:	cpp.ifcxx
 */

#ifndef ndds_cpp_h
#define ndds_cpp_h


/* These defines automatically set up the compiler for Windows users */
/* Must be VS2003 or greater, and not compiling for WinCE */
#if defined(_WIN32) && !defined(RTI_WINCE) && _MSC_VER > 1310 && !defined(RTI_WIN32)
	#define RTI_WIN32
	#ifdef _DLL /* compiling against DLL version of the CRT */
		#define NDDS_DLL_VARIABLE
		#ifdef _DEBUG
			#pragma comment( lib, "nddscppd.lib")
		#else
			#pragma comment( lib, "nddscpp.lib")
		#endif /* _DEBUG */
	#else  /* static libs */
		#ifdef _DEBUG
			#pragma comment( lib, "nddscppzd.lib")
		#else
			#pragma comment( lib, "nddscppz.lib")
		#endif /* #ifdef _DEBUG */
	#endif /* _DLL */
#endif /* defined(_WIN32) && !defined(RTI_WINCE) && _MSC_VER > 1310 */

  #ifdef NDDS_DLL_VARIABLE
    #define RTI_dds_cpp_DLL_VARIABLE
    #define RTI_dds_c_DLL_VARIABLE
    #define RTI_disc_DLL_VARIABLE
    #define RTI_pres_DLL_VARIABLE
    #define RTI_writer_history_DLL_VARIABLE
    #define RTI_commend_DLL_VARIABLE
    #define RTI_mig_DLL_VARIABLE
    #define RTI_netio_DLL_VARIABLE
    #define RTI_transport_DLL_VARIABLE
    #define RTI_event_DLL_VARIABLE
    #define RTI_cdr_DLL_VARIABLE
    #define RTI_reda_DLL_VARIABLE
    #define RTI_dl_driver_DLL_VARIABLE
    #define RTI_osapi_DLL_VARIABLE
    #define RTI_clock_DLL_VARIABLE
    #define RTI_log_DLL_VARIABLE
  #endif

  #ifndef dds_cpp_dll_h
    #include "ndds/dds_cpp/dds_cpp_dll.h"
  #endif
  #ifndef osapi_type_h
    #include "ndds/osapi/osapi_type.h"
  #endif
  #ifndef ndds_c_h
    #include "ndds/ndds_c.h"
  #endif
  #ifndef dds_cpp_infrastructure_h
    #include "ndds/dds_cpp/dds_cpp_infrastructure.h"
  #endif
  #ifndef dds_cpp_topic_h
    #include "ndds/dds_cpp/dds_cpp_topic.h"
  #endif
  #ifndef dds_cpp_publication_h
    #include "ndds/dds_cpp/dds_cpp_publication.h"
  #endif
  #ifndef dds_cpp_subscription_h
    #include "ndds/dds_cpp/dds_cpp_subscription.h"
  #endif
  #ifndef dds_cpp_domain_h
    #include "ndds/dds_cpp/dds_cpp_domain.h"
  #endif
  #ifndef dds_cpp_data_h
    #include "ndds/dds_cpp/dds_cpp_data.h"
  #endif
  #ifndef dds_cpp_builtin_h
    #include "ndds/dds_cpp/dds_cpp_builtin.h"
  #endif
  #ifndef dds_cpp_builtintypes_h
    #include "ndds/dds_cpp/dds_cpp_builtintypes.h"
  #endif 
  #ifndef dds_cpp_dynamicdata_h
    #include "ndds/dds_cpp/dds_cpp_dynamicdata.h"
  #endif
  #ifndef dds_cpp_asyncwaitset_h
    #include "ndds/dds_cpp/dds_cpp_asyncwaitset.h"
  #endif
  #ifndef ndds_config_cpp_h
    #include "ndds/ndds_config_cpp.h"
  #endif
  #ifndef ndds_utility_cpp_h
    #include "ndds/ndds_utility_cpp.h"
  #endif
  #ifndef ndds_writerhistory_cpp_h
    #include "ndds/ndds_writerhistory_cpp.h"
  #endif
  #ifndef ndds_transport_cpp_h
    #include "ndds/ndds_transport_cpp.h"
  #endif
  #ifndef ndds_discovery_cpp_h
    #include "ndds/ndds_discovery_cpp.h"
  #endif

#endif /* ndds_cpp_h */
