/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_octet_buffer.h    generated by: makeheader    Fri Feb 16 13:51:58 2018
 *
 *		built from:	octet_buffer.ifc
 */

#ifndef dds_c_octet_buffer_h
#define dds_c_octet_buffer_h


  #ifndef dds_c_dll_h
    #include "dds_c/dds_c_dll.h"
  #endif
  #ifndef dds_c_common_h
    #include "dds_c/dds_c_common.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif

extern DDSCDllExport unsigned char* 
DDS_OctetBuffer_alloc(unsigned int size);

extern DDSCDllExport unsigned char* 
DDS_OctetBuffer_dup(const unsigned char* buffer, unsigned int size);

extern DDSCDllExport void 
DDS_OctetBuffer_free(unsigned char* buffer);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dds_c_octet_buffer_h */
