/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_asyncwaitset_impl.h    generated by: makeheader    Fri Feb 16 13:51:57 2018
 *
 *		built from:	asyncwaitset_impl.ifc
 */

#ifndef dds_c_asyncwaitset_impl_h
#define dds_c_asyncwaitset_impl_h



#ifndef dds_c_infrastructure_h
  #include "dds_c/dds_c_infrastructure.h"
#endif

#ifndef dds_c_domain_h
  #include "dds_c/dds_c_domain.h"
#endif

#ifndef dds_c_asyncwaitset_h
  #include "dds_c/dds_c_asyncwaitset.h"
#endif


#ifdef __cplusplus
    extern "C" {
#endif
        

extern DDSCDllExport 
DDS_AsyncWaitSet * DDS_AsyncWaitSet_newI(
        DDS_DomainParticipantFactory *factory,
        const struct DDS_AsyncWaitSetProperty_t *awsProperty,
        struct DDS_AsyncWaitSetListener *listener,
        struct DDS_ThreadFactory *threadFactory,
        REDAOrderedDataTypeCompareWithUserDataFunction compareHandler,
        void *compareUserData);

extern DDSCDllExport 
DDS_WaitSet * DDS_AsyncWaitSet_get_waitsetI(
    DDS_AsyncWaitSet *self);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dds_c_asyncwaitset_impl_h */
